//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimupaAPI.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        public int attribute_id { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public string screen { get; set; }
        public string operating_system { get; set; }
        public string camera_after { get; set; }
        public string camera_before { get; set; }
        public string cpu { get; set; }
        public string battery_capacity { get; set; }
        public string size { get; set; }
        public Nullable<int> pro_id { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
