//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimupaAPI.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int banner_id { get; set; }
        public string banner_name { get; set; }
        public string link { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
