//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimupaAPI.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int news_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string content { get; set; }
        public string images { get; set; }
        public string image_detail { get; set; }
        public string createby { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
