//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimupaAPI.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_detail
    {
        public int orderDetail_id { get; set; }
        public int quantity { get; set; }
        public double total_price { get; set; }
        public double sale_price { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> pro_id { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
