//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimupaAPI.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductRam
    {
        public int productRam_id { get; set; }
        public double ram_price { get; set; }
        public double ram_sale_price { get; set; }
        public Nullable<int> pro_id { get; set; }
        public Nullable<int> ram_id { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Ram Ram { get; set; }
    }
}
